

server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

spring:
  application:
    name: register-repository
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
  flyway:
    enabled: true
  mail:
    default-encoding: UTF-8

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
          semaphore:
            maxConcurrentRequests: 5000
    REPO-SERVER:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 5000

feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    fetch-registry: true





